package dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import dao.pushVideo;
import dao.lghTable;

import dao.pushVideoDao;
import dao.lghTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pushVideoDaoConfig;
    private final DaoConfig lghTableDaoConfig;

    private final pushVideoDao pushVideoDao;
    private final lghTableDao lghTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pushVideoDaoConfig = daoConfigMap.get(pushVideoDao.class).clone();
        pushVideoDaoConfig.initIdentityScope(type);

        lghTableDaoConfig = daoConfigMap.get(lghTableDao.class).clone();
        lghTableDaoConfig.initIdentityScope(type);

        pushVideoDao = new pushVideoDao(pushVideoDaoConfig, this);
        lghTableDao = new lghTableDao(lghTableDaoConfig, this);

        registerDao(pushVideo.class, pushVideoDao);
        registerDao(lghTable.class, lghTableDao);
    }
    
    public void clear() {
        pushVideoDaoConfig.getIdentityScope().clear();
        lghTableDaoConfig.getIdentityScope().clear();
    }

    public pushVideoDao getPushVideoDao() {
        return pushVideoDao;
    }

    public lghTableDao getLghTableDao() {
        return lghTableDao;
    }

}
