package dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LGH_TABLE.
 */
public class lghTable {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String address;
    /** Not-null value. */
    private String head_url;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public lghTable() {
    }

    public lghTable(Long id) {
        this.id = id;
    }

    public lghTable(Long id, String name, String address, String head_url) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.head_url = head_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getHead_url() {
        return head_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHead_url(String head_url) {
        this.head_url = head_url;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
