package dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PUSH_VIDEO.
 */
public class pushVideo {

    private Long d_id;
    /** Not-null value. */
    private String d_area;
    /** Not-null value. */
    private String d_content;
    /** Not-null value. */
    private String d_directed;
    /** Not-null value. */
    private String d_dayhits;
    /** Not-null value. */
    private String d_true_play_url;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public pushVideo() {
    }

    public pushVideo(Long d_id) {
        this.d_id = d_id;
    }

    public pushVideo(Long d_id, String d_area, String d_content, String d_directed, String d_dayhits, String d_true_play_url) {
        this.d_id = d_id;
        this.d_area = d_area;
        this.d_content = d_content;
        this.d_directed = d_directed;
        this.d_dayhits = d_dayhits;
        this.d_true_play_url = d_true_play_url;
    }

    public Long getD_id() {
        return d_id;
    }

    public void setD_id(Long d_id) {
        this.d_id = d_id;
    }

    /** Not-null value. */
    public String getD_area() {
        return d_area;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD_area(String d_area) {
        this.d_area = d_area;
    }

    /** Not-null value. */
    public String getD_content() {
        return d_content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD_content(String d_content) {
        this.d_content = d_content;
    }

    /** Not-null value. */
    public String getD_directed() {
        return d_directed;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD_directed(String d_directed) {
        this.d_directed = d_directed;
    }

    /** Not-null value. */
    public String getD_dayhits() {
        return d_dayhits;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD_dayhits(String d_dayhits) {
        this.d_dayhits = d_dayhits;
    }

    /** Not-null value. */
    public String getD_true_play_url() {
        return d_true_play_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setD_true_play_url(String d_true_play_url) {
        this.d_true_play_url = d_true_play_url;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
